parameters:
#    viva_common.example.class: Viva\CommonBundle\Example

services:
#    viva_common.example:
#        class: %viva_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
